available_text_models: ["gpt-4-1106-preview", "gpt-4-vision-preview", "gpt-4", "gpt-4o", "o1-preview", "o1-mini"]

info:
  gpt-4-1106-preview:
    type: chat_completion
    name: GPT4 Turbo
    description: GPT-4 Turbo is a <b>faster</b> and <b>cheaper</b> version of GPT-4. It's as smart as GPT-4, so you should use it instead of GPT-4.

    price_per_1000_input_tokens: 0.01
    price_per_1000_output_tokens: 0.03

    scores:
      smart: 5
      fast: 4
      cheap: 3
  
  gpt-4-vision-preview:
    type: chat_completion
    name: GPT4 Vision
    description: Ability to <b>understand images</b>, in addition to all other GPT-4 Turbo capabilties.

    price_per_1000_input_tokens: 0.01
    price_per_1000_output_tokens: 0.03

    scores:
      smart: 5
      fast: 4
      cheap: 3

  gpt-4:
    type: chat_completion
    name: GPT4
    description: GPT-4 is the <b>smartest</b> and most advanced model in the world. But it is slower and not as cost-efficient as ChatGPT. Best choice for <b>complex</b> intellectual tasks.

    price_per_1000_input_tokens: 0.03
    price_per_1000_output_tokens: 0.06

    scores:
      Smart: 5
      Fast: 2
      Cheap: 2

  gpt-4o:
    type: chat_completion
    name: GPT4o
    description: GPT-4o is a special variant of GPT-4 designed for optimal performance and accuracy. Suitable for complex and detailed tasks.

    price_per_1000_input_tokens: 0.03
    price_per_1000_output_tokens: 0.06

    scores:
      smart: 5
      fast: 2
      cheap: 2
  
  o1-preview:
    type: chat_completion
    name: GPT-o1
    description: an early preview of our o1 model, designed to reason about hard problems using broad general knowledge about the world.

    price_per_1000_input_tokens: 0.03
    price_per_1000_output_tokens: 0.06

    scores:
      smart: 5
      fast: 1
      cheap: 1
  
  o1-mini:
    type: chat_completion
    name: GPT-o1-mini
    description: a faster and cheaper version of o1, particularly adept at coding, math, and science tasks where extensive general knowledge isn't required.

    price_per_1000_input_tokens: 0.03
    price_per_1000_output_tokens: 0.06

    scores:
      smart: 5
      fast: 2
      cheap: 2

  dalle-2:
     type: image
     price_per_1_image: 0.018  # 512x512

  whisper:
    type: audio
    price_per_1_min: 0.006
